import { Activity } from "../types/activity.types";

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: "act-001",
    orderNumber: "OS-2026-081",
    name: "Pintura Epóxi no Tanque de Decantação T-01",
    serviceType: "Pintura Epóxi",
    tags: [
      { id: "tag-1", code: "TK-DEC-01" },
      { id: "tag-2", code: "VLV-TK01-A" },
    ],
    location: {
      area: "Área Industrial Norte",
      local: "Pátio de Tanques",
      equipment: "Tanque T-01",
    },
    description: "Preparação de superfície com hidrojateamento e aplicação de fundo primer epóxi.",
    status: "em_andamento",
    priority: "alta",
    assignedTo: "Carlos Andrade",
    team: "Equipe Alfa - Pintura Pesada",
    progressPercentage: 45,
    schedule: {
      plannedStartDate: "2026-08-10",
      plannedEndDate: "2026-08-20", // Atrasada (ref: 2026-08-23)
      actualStartDate: "2026-08-11",
      teamName: "Equipe Alfa - Pintura Pesada",
    },
    consumptions: [
      {
        id: "c-1",
        materialId: "mat-1",
        materialName: "Primer Epóxi Poliamida",
        quantity: 36,
        unit: "L",
        registeredAt: "2026-08-15 14:30",
        registeredBy: "Carlos Andrade",
      },
    ],
    history: [],
    createdAt: "2026-08-01",
    updatedAt: "2026-08-15",
  },
  {
    id: "act-002",
    orderNumber: "OS-2026-085",
    name: "Tratamento Anticorrosivo Tubulação de Incêndio",
    serviceType: "Pintura Poliuretano (PU)",
    tags: [{ id: "tag-3", code: "TUB-INC-L2" }],
    location: {
      area: "Utilidades",
      local: "Linha Principal de Incêndio",
      equipment: "Tubulação 6 pol",
    },
    description: "Lixamento mecânico e demão intermediária poliuretano alifático.",
    status: "programada",
    priority: "media",
    assignedTo: "Marcos Souza",
    team: "Equipe Beta - Tubulações",
    progressPercentage: 0,
    schedule: {
      plannedStartDate: "2026-08-23", // Hoje
      plannedEndDate: "2026-08-30",
      teamName: "Equipe Beta - Tubulações",
    },
    consumptions: [],
    history: [],
    createdAt: "2026-08-12",
    updatedAt: "2026-08-12",
  },
  {
    id: "act-003",
    orderNumber: "OS-2026-079",
    name: "Pintura de Proteção Térmica na Caldeira Auxiliar",
    serviceType: "Pintura Alta Temperatura (Silicone)",
    tags: [{ id: "tag-4", code: "CALD-AUX-02" }],
    location: {
      area: "Geração de Vapor",
      local: "Casa de Caldeiras",
      equipment: "Caldeira B",
    },
    description: "Aplicação de tinta silicone alta temperatura até 400°C.",
    status: "concluida",
    priority: "alta",
    assignedTo: "Roberto Silva",
    team: "Equipe Alfa - Pintura Pesada",
    progressPercentage: 100,
    schedule: {
      plannedStartDate: "2026-08-01",
      plannedEndDate: "2026-08-10",
      actualStartDate: "2026-08-01",
      actualEndDate: "2026-08-09",
      teamName: "Equipe Alfa - Pintura Pesada",
    },
    consumptions: [],
    history: [],
    createdAt: "2026-07-28",
    updatedAt: "2026-08-09",
  },
  {
    id: "act-004",
    orderNumber: "OS-2026-092",
    name: "Revitalização da Estrutura Metálica do Galpão",
    serviceType: "Tratamento Manual/Mecânico (St 2 / St 3)",
    tags: [{ id: "tag-5", code: "ESTR-GALP-04" }],
    location: {
      area: "Logística",
      local: "Galpão 4",
      equipment: "Vigas I e Pilares",
    },
    description: "Tratamento de pontos de ferrugem localizada e pintura sintética cinza.",
    status: "pausada",
    priority: "baixa",
    assignedTo: "Marcos Souza",
    team: "Equipe Beta - Tubulações",
    progressPercentage: 20,
    schedule: {
      plannedStartDate: "2026-08-14",
      plannedEndDate: "2026-08-22", // Atrasada
      actualStartDate: "2026-08-15",
      teamName: "Equipe Beta - Tubulações",
    },
    consumptions: [],
    history: [],
    createdAt: "2026-08-10",
    updatedAt: "2026-08-18",
  },
  {
    id: "act-005",
    orderNumber: "OS-2026-099",
    name: "Pintura de Demarcação Viária e Segurança",
    serviceType: "Demarcação e Sinalização",
    tags: [{ id: "tag-6", code: "DEM-VIAR-CENTRAL" }],
    location: {
      area: "Área Industrial Norte",
      local: "Vias Internas",
      equipment: "Piso Asfáltico / Concreto",
    },
    description: "Pintura acrílica refletiva amarela e zebrada nos acessos de empilhadeiras.",
    status: "programada",
    priority: "urgente",
    assignedTo: "Carlos Andrade",
    team: "Equipe Geral",
    progressPercentage: 0,
    schedule: {
      plannedStartDate: "2026-08-23", // Hoje
      plannedEndDate: "2026-08-27",
      teamName: "Equipe Geral",
    },
    consumptions: [],
    history: [],
    createdAt: "2026-08-20",
    updatedAt: "2026-08-20",
  },
  {
    id: "act-006",
    orderNumber: "OS-2026-105",
    name: "Aplicação de Poliuretano na Escada de Acesso",
    serviceType: "Pintura Poliuretano (PU)",
    tags: [{ id: "tag-7", code: "ESC-AC-PR" }],
    location: {
      area: "Utilidades",
      local: "Pipe Rack Principal",
      equipment: "Escada Metálica",
    },
    description: "Demão final de acabamento poliuretano brilhante cinza claro.",
    status: "em_andamento",
    priority: "media",
    assignedTo: "Roberto Silva",
    team: "Equipe Alfa - Pintura Pesada",
    progressPercentage: 60,
    schedule: {
      plannedStartDate: "2026-08-21",
      plannedEndDate: "2026-08-26",
      teamName: "Equipe Alfa - Pintura Pesada",
    },
    consumptions: [],
    history: [],
    createdAt: "2026-08-18",
    updatedAt: "2026-08-22",
  },
];
